name: CI/CD Dispatch on PR to Main

on:
  pull_request:
    branches:
      - main  # Trigger when a PR is opened into main

jobs:
  detect-source-and-run:
    runs-on: ubuntu-latest
    outputs:
      source_branch: ${{ steps.get_branch.outputs.source_branch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get source branch
        id: get_branch
        run: echo "source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

  dev:
    if: ${{ needs.detect-source.outputs.source_branch == 'dev' }}
    needs: detect-source
    uses: ./.github/workflows/buildPush.yaml
    with:
      image_tag_prefix: dev
      version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}

  staging:
    if: ${{ needs.detect-source.outputs.source_branch == 'staging' }}
    needs: detect-source
    uses: ./.github/workflows/buildPush.yaml
    with:
      image_tag_prefix: staging
      version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}

  prod:
    if: ${{ needs.detect-source.outputs.source_branch == 'prod' }}
    needs: detect-source
    uses: ./.github/workflows/buildPush.yaml
    with:
      image_tag_prefix: prod
      version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}
#added comment