name: CI/CD Dispatch on PR to Main

on:
  pull_request:
    branches:
      - main  # Trigger when a PR is opened into main

jobs:
  detect-source-and-run:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout the repo so local workflows are accessible
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Step 2: Check if AWS secrets are set
      - name: Validate AWS Secrets
        run: |
          if [ -z "${{ secrets.REGION }}" ]; then
            echo "❌ REGION is missing"
            exit 1
          fi
          if [ -z "${{ secrets.ACCESSID }}" ]; then
            echo "❌ ACCESSID is missing"
            exit 1
          fi
          if [ -z "${{ secrets.ACCESSSECRET }}" ]; then
            echo "❌ ACCESSSECRET is missing"
            exit 1
          fi
          echo "✅ All required AWS secrets are set"

      # ✅ Step 3: Get the source branch of the PR (e.g., dev, staging, prod)
      - name: Get source branch
        id: source
        run: |
          echo "source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

      # ✅ Step 4: Call the dev workflow if the PR is from dev
      - name: Call dev workflow
        if: ${{ github.head_ref == 'dev' }}
        uses: ./.github/workflows/buildPush.yaml
        with:
          image_tag_prefix: dev
          version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}

      # ✅ Step 5: Call the staging workflow if the PR is from staging
      - name: Call staging workflow
        if: ${{ github.head_ref == 'staging' }}
        uses: ./.github/workflows/buildPush.yaml
        with:
          image_tag_prefix: staging
          version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}

      # ✅ Step 6: Call the prod workflow if the PR is from prod
      - name: Call prod workflow
        if: ${{ github.head_ref == 'prod' }}
        uses: ./.github/workflows/buildPush.yaml
        with:
          image_tag_prefix: prod
          version_suffix: pr${{ github.event.pull_request.number }}-${{ github.sha }}