name: CI/CD (Prod)

on:
  push:
    tags:
      - 'v*.*.*'  # 🆕 Triggers on semantic version tags like v1.0.0

jobs:
  call-reusable:
    uses: ./.github/workflows/buildPush.yaml
    with:
      image_tag_prefix: prod
      version_suffix: ${{ github.ref_name }}  # 🆕 Automatically uses the tag name like v1.2.3
# new comment